### ISSUE TITLE
GTK run issue on lower version of GLib

### ISSUE THREAD

**Issue by srijan023** [srijan023/seamless_sync#8]
7 |   app = gtk_application_new("org.tu.seamlessSync", G_APPLICATION_DEFAULT_FLAGS);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                    G_APPLICATION_GET_CLASS
Write the possible fix for this and merge it.

**Comment by abhinaya-aryal** [comment]
Note: If the above compilation does not work due to an error regarding G_APPLICATION_DEFAULT_FLAGS this could be due to your OS providing an older version of GLib. For GLib versions older than 2.74 you will need to replace G_APPLICATION_DEFAULT_FLAGS with G_APPLICATION_FLAGS_NONE in this example, and others in this documentation. For more information on how to compile a GTK application, please refer to the [Compiling GTK Applications](https://docs.gtk.org/gtk4/compiling.html) section in this reference.

"As an official note, the possible ways are either updating GLib or using G_APPLICATION_FLAGS_NONE."
